#ifndef ACTIONTYPE_HPP
#define ACTIONTYPE_HPP

enum ActionType {
    NORMAL_DICE_ROLL,
    TAKE_LOAN,
    PAY_LOAN,
    BUY_HOUSE,
    SELL_HOUSE,
    EXCHANGE,
    OUT_OF_JAIL_ROLL_DICE,
    USE_CARD_TO_GET_FREE,
    PAY_AND_GET_FREE,
    SHOW_BOARD,
    CONFIRM,
    CANCEL    
};

#endif